### ISSUE TITLE
Having a blueprint system for objects

### ISSUE THREAD

**Issue by Raj2032** [katharostech/arsenal#16]
So lets say that I created a model within Arsenal and then in the main game, I import the same models in multiple areas. If I wanted suddenly update/change the model and/or the code that it is attached to there should be a blueprint where I can apply the change once and it updates all of the same models across the entire scene.

If it doesn't make sense let me know and I will try and rephrase that.

**Comment by opax7** [comment]
Labeling this as a question for now until we can discuss whether this needs to be a feature or if this should be accomplished through program design, or would be handled inherently by the engine implementation.

**Comment by Raj2032** [comment]
@opax7 Cool

**Comment by opax7** [comment]
#11 has already been created by Zicklag which covers this requirement. So yes it is a feature/enhancement that we will work into the design. We will work to refine the story a bit since it is somewhat general.

Closing this question out as tracked under issue #11. 
Locking this conversation to minimize cross talk. If you want to correspond on this topic, please do so under issue #11.
