### ISSUE TITLE
Feature suggestion: Have a good lighting style just like Godot and Unity

### ISSUE THREAD

**Issue by Raj2032** [katharostech/arsenal#4]
The problem with Armory at this stage is the way how the default camera and lighting setup is terrible, Both Godot and Unity do a better job with its lighting system I hope that Arsenal can use something similar to Godot and Unity.

**Comment by zicklag** [comment]
Right now we aren't ready to deal with anything rendering related. That will come, but it will also be more dependent on getting the needed features into the [Amethyst](https://amethyst.rs/) engine that we are building on top of.

For now I'm going to close this issue. Once we get more of the basic foundation laid down we can discuss higher level aspects such as rendering. Also I'm going to start working on laying out an initial [roadmap](https://github.com/katharostech/arsenal/milestones) so that you can see what we will be working on.

**Comment by zicklag** [comment]
Even if we don't work on it now, I am curious, what exactly is the issue you have with Armory's lighting and camera setup? Is it a problem in the way that things look, or in the way that objects are placed when designing the scene? I just realized that you may not have meant rendering as much as UX for placing lights and cameras.

**Comment by Raj2032** [comment]
@zicklag Hi zicklag, when I used Unity and Godot, if I added a sun (or spot light or anything similar) (without even pressing the _play_ button) then the sun's lighting, would immediately show, whereas on Armory it doesn't immediately show unless if you play the game, which is a bit of a disappointment as I would like to continuously play with the sun's lighting without having to press the play button, and then end it and then make small incremental changes etc.

Plus Godot and Unity comes with a default sky and all that but with Armory you have to make it yourself which is a disadvantage.

**Comment by zicklag** [comment]
OK, that makes sense.

Would it satisfy you for this use-case if the lights, and other objects, in the scene were synced live from the Blender interface to your running game? For example:

1. You place your lights in Blender
2. You run the game from Blender and it starts a second window that shows your running game ( just like Armory )
3. You switch back to Blender without closing the game
4. You rotate or move you light in Blender and the changes are immediately reflected in your running game

This kind of workflow is something that we think that we can accomplish and that I think would be a big UX improvement over the build->run->test->repeat workflow.

**Comment by Raj2032** [comment]
@zicklag Yeah that seems like a pretty good idea but personally I think it is better to automatically show up the lighting within the scene (without starting the game) so that I don't have to keep switching between windows to change the lighting.

**Comment by zicklag** [comment]
The difficulty with displaying it in the viewport is that we may not be able to get Blender to render the viewport so that it looks exactly like the game. Its one of the trad-offs of using Blender as the primary game building interface. Armory has an open [issue](https://github.com/armory3d/armory/issues/1098) for doing something similar, though, so we'll have to look into that.

I'll create issues for live sync and the viewport renderer and link them back here so that we don't lose the idea. Thanks for the feature suggestion. :slightly_smiling_face:

**Comment by zicklag** [comment]
Tracking this in issues #14 and #15.

**Comment by Raj2032** [comment]
@zicklag 

> I'll create issues for live sync and the viewport renderer and link them back here so that we don't lose the idea. Thanks for the feature suggestion. 🙂

You're welcome glad to help you out.
