### ISSUE TITLE
PhysX physics engine

### ISSUE THREAD

**Issue by Raj2032** [katharostech/arsenal#77]
Would Arsenal support/use the PhysX physics engine as I heard this is pretty good?

**Comment by zicklag** [comment]
I won't say that it is out of the question, but there are some reasons that we would be more inclined **not** to:

* While PhysX was recently made Open Source, I have heard that their EULA was not changed for the XBox One, Playstation 4, and the Nintendo Switch. We would need to do some more investigation to make sure. That could cause problems for Arsenal as an Open Source project.
* We would have to make sure that it could support Emscripten so that it could run in web browsers.
* Nvidia is, in general, a more private and closed off company which makes us hesitant to use their software for fear that their private interests will get in the way of open collaboration.

The first physics engine we will be trying out will most-likely be [nphysics](https://nphysics.org/) because it is written in Rust. If that doesn't suite our needs or if we decide that it would be beneficial, we may decide to integrate [Bullet](https://pybullet.org/wordpress/) as well.

Even if we don't support PhysX out-of-the-box, Arsenal will be designed such that if you have the expertise and you want or need to integrate it yourself, there would be nothing stopping you from doing that.

**Comment by zicklag** [comment]
PhysX is a non-goal for now. We will most likely be using [Rapier](https://www.rapier.rs/) which has a Bevy integration.
